### ISSUE TITLE
Classic wallet quits after trying to prove balance on view-only wallet

### ISSUE THREAD

**Issue by KarboDuck** [seredat/karbowanecwallet#13]
1. Open view-only wallet in Classic 1.3.5
2. Choose in Menu: Wallet -> Confirm Balance.
3. Correct error dialog appears (not possible to prove balance in view only wallet), but after closing it main app quits without any warning.

**Comment by aivve** [comment]
Fixed in https://github.com/seredat/karbowanecwallet/commit/c3e732f4a2f5b94124c5e205a791bf5a2f6586ab
