### ISSUE TITLE
.wallet.temp file created if .wallet doesn't exist while opening from recent wallets menu

### ISSUE THREAD

**Issue by KarboDuck** [seredat/karbowanecwallet#14]
1. Open couple of wallets to have them in "recently opened" menu.
2. Delete (move) any one wallet and try to open it from recent menu.
3. After nothing happened open any other wallet.

Result: empty file *.wallet.temp created in directory where non-existent wallet (step 2) was expected.

Expected: No *.wallet.temp file should be created.

Info: Classic 1.3.6 wallet; Windows 10

**Comment by aivve** [comment]
Ty! Will fix it.
