### ISSUE TITLE
Build error in windows

### ISSUE THREAD

**Issue by lynAzrael** [seredat/karbowanecwallet#15]
when i execute the make command after "cmake .." , it returns the error info.

-- Generating done
-- Build files have been written to: H:/karbowanecwallet/build
make: *** No targets specified and no makefile found.  Stop.

What's the reason of this issue?

**Comment by aivve** [comment]
I don't know, you can use MSVC or QT Creator to build it.

**Comment by lynAzrael** [comment]
ok,  I will try it again. Thanks a lot.
