### ISSUE TITLE
Small graphical glitches in "Recent wallets" submenu

### ISSUE THREAD

**Issue by KarboDuck** [seredat/karbowanecwallet#34]
1. Launch wallet application.
2. Click on File menu.

Basically File menu for some reason just cut from right side.

Only occurs on first time invoking File menu. Click menu File second time and glitches are gone.

![image](https://user-images.githubusercontent.com/53382906/73297534-6afd8480-4214-11ea-9dc1-d051b2062a9b.png)

**Comment by aivve** [comment]
Ty, it looks ok on my wallet, hard to reproduce. Maybe it needs time to fully load? 🤔

**Comment by KarboDuck** [comment]
Couldn't reproduce anymore in v 1.4.9.
