### ISSUE TITLE
Impossible to get proof of balance on offline PC

### ISSUE THREAD

**Issue by KarboDuck** [seredat/karbowanecwallet#39]
1. Disable Internet connection, or put Karbo wallet behind firewall.
2. Launch wallet and try to get proof of balance.

![Annotation 2021-01-11 222558](https://user-images.githubusercontent.com/53382906/104234702-7ca75e80-545c-11eb-8640-c3fd4faae0a4.jpg)

Result: "Get proof of balance" menu item is greyed out even if full and up to date blockchain present on offline PC.

Expecatation: Be able to get proof of balance on offline PC with fresh copy of blockchain.

**Comment by aivve** [comment]
Fixed in afff427a19e0277ad0ec59673f458984de9135d4
