### ISSUE TITLE
Send button inactive when generating raw transaction offline

### ISSUE THREAD

**Issue by KarboDuck** [seredat/karbowanecwallet#42]
1. Disconnect from Internet or put wallet behind firewall.
2. Launch Wallet.
3. On send tab check "Prepare transaction but do not relay" and finish filling tx (destination and amount)

Result: Send button is greyed out and not available.

Expected: Send button is available and creates raw transaction.

**Comment by aivve** [comment]
Have to think about it as we don't want to allow users to be able to send from an unsynced wallet to prevent invalid txs due to collision if they have sent the same coins elsewhere.

**Comment by aivve** [comment]
Have to check and fix offline work with daemon instead of builtin node
