### ISSUE TITLE
Sending tx with default "0 amount" not handling correctly

### ISSUE THREAD

**Issue by KarboDuck** [seredat/karbowanecwallet#44]
1. Open classic Karbo Wallet v 1.4.9.
2.  On send tab fill in address and press send.

Result: 
Wallet shows "Sending transactions" status but doesn't do anything probably because by default amount was set to 0.

![KarbowanecWallet_Dyg2Rf8aob](https://user-images.githubusercontent.com/53382906/104651526-72859a00-56c0-11eb-94c2-367572d01a8b.png)

It is almost non-issue, because wallet can be used further normally and after editing amount send will work correctly.

Expected: 
Warning about no amount specified. Or better just highlight "Amount" field with red color blink.

Also look at [issue43](https://github.com/seredat/karbowanecwallet/issues/43). Check should execute before asking for password and payment id, not after.

**Comment by aivve** [comment]
Should be fixed in f8fbed7 and db7424c
