### ISSUE TITLE
"Pending" amount of change stucks if wallet closed shortly after sending tx

### ISSUE THREAD

**Issue by KarboDuck** [seredat/karbowanecwallet#45]
1. Open Karbo Wallet 1.4.9
2. Create and send any transaction that will lead to locking some amount in "Pending"
3. Close and reopen application

![KarbowanecWallet_R3QSFx4DnT](https://user-images.githubusercontent.com/53382906/104651995-1b33f980-56c1-11eb-956b-36b4374b9e72.png)

Result:
Pending amount is stuck no matter how much time is passed. Can be fixed by wallet reset.

Pending obviously will not stuck if wallet was not closed until tx is confirmed enough times.

Not introduced in recent wallets, was working this way for quite some time.

Expected:
Pending amount shouldn't stuck even if wallet closed shortly after sending tx.

**Comment by aivve** [comment]
Will look at it, it must be something deep under the hood.
