### ISSUE TITLE
Rename send button when constructing raw transaction

### ISSUE THREAD

**Issue by KarboDuck** [seredat/karbowanecwallet#46]
1. Launch Karbo Wallet 1.4.9
2. Check "Prepare transaction but do not relay"

Result:
Send button is still called Send and might confuse some users.

Expected:
Send button should change name to something like "Show raw tx" or maybe just "Show" and not suggest that transaction will be send after pressing it.

**Comment by aivve** [comment]
Good point, it can be done.

**Comment by aivve** [comment]
It's done in 8d9c46d
