### ISSUE TITLE
Small glitch in optimization dialog

### ISSUE THREAD

**Issue by KarboDuck** [seredat/karbowanecwallet#47]
1. Click Settings - Optimization
2. Click Optimization Target dropdown menu

Result: small glitch.  (also some different glitches after selecting different targets and reopening dropdown menu)

![image](https://user-images.githubusercontent.com/53382906/107350161-befea280-6ad1-11eb-9527-b01b376f399e.png)

**Comment by aivve** [comment]
TY, this is somehow related to QT version, I guess, could be also elsewhere, in other dropdowns.

**Comment by aivve** [comment]
Seems to be fixed in a59e6ba
