### ISSUE TITLE
MX-Linux Fails to install Karbo Gui Wallet

### ISSUE THREAD

**Issue by Gapcoin1** [seredat/karbowanecwallet#50]
Seems probably only Ubuntu can install the QT GUI Karbo.

Error : 
Dependency is not satisfiable:

libgcc-s1 (>=3.0)

It's install however it must be different .deb Versioning for other Linux .deb Packages than for Ubuntu

All other Karbo Gui's fail to install also on MX-Linux with other errors but similar I think

**Comment by aivve** [comment]
TY, probably it is Github Actions machines to blame, they constantly update everything, would be easier to compile yourself from sources for this flavour of Linux

**Comment by Gapcoin1** [comment]
Thanks, hopefully you can help me Compile it myself.  It used to Compile for me probably 2 years ago, I mined it long time ago when it was still possible to Solo Mine and you had the GUI built in Miner.  

I think It used the GUI Miner built in which had your Pools too.  I cannot even install the GUI using the same Linux OS anymore or Compile.  I think Ubuntu is problem.  I don't like the Ubuntu/Debian Stream.  MX-Linux and Trisquel OS are better to Code for.  

![Screenshot at 2021-05-16 20-16-07](https://user-images.githubusercontent.com/68176698/118403534-63a6f800-b65e-11eb-893e-02a903ba96b7.png)
![Screenshot at 2021-05-16 20-22-12](https://user-images.githubusercontent.com/68176698/118403605-b54f8280-b65e-11eb-8a7c-35f553730766.png)

**Comment by aivve** [comment]
You need to clone with subprojects or clone https://github.com/seredat/karbowanec/ into `cryptonote` folder. Also I think the old version of the wallet (that run on your OS) should work with a remote node (you can change it in Connection settings) you can find some nodes here https://explorer.karbo.org/#nodes

**Comment by Gapcoin1** [comment]
Actually I have never Compiled the GUI, I only Compiled Karbowanec and it still compiles the Daemon.

I don't understand those instructions, I am not sure why

Thanks
