### ISSUE TITLE
Аварийный останов при подтверждении баланса

### ISSUE THREAD

**Issue by Motsyo** [seredat/karbowanecwallet#56]
https://bugzilla.altlinux.org/41659
Для воспроизведения необходимо:
1. Запустить в терминале KarbowanecWallet
2. В меню: "Кошелек" -> "Подтверждение баланса"
3. Перед значением "0.000000000000 KRB" начать вводить цифры

Результат:
    сообщение в терминале:
        terminate called after throwing an instance of 'std::runtime_error'
            what():  Zero balance
        Аварийный останов

Актуально и для 1.7.2, и для 1.7.3.
[strace.log](https://github.com/seredat/karbowanecwallet/files/7796663/strace.log)

**Comment by aivve** [comment]
Спасибо. Как-то не пришло мне в голову что можно попытаться подтвердить нулевой баланс.

**Comment by aivve** [comment]
Fixed in f896b4f and 695ede3

**Comment by Motsyo** [comment]
> Спасибо. Как-то не пришло мне в голову что можно попытаться подтвердить нулевой баланс.

Отдел контроля в ALT-e те еще затейники...
