### ISSUE TITLE
Cannot open wallet after computer crash

### ISSUE THREAD

**Issue by scissors14** [seredat/karbowanecwallet#60]
My computer lost power now I cannot open the wallet anymore. I've reinstalled, uninstalled, reinstalled, the app does some stuff when I open the exe but nothing comes up.

**Comment by aivve** [comment]
In the folder where your wallet is stored look for temporary files, if present rename to .wallet and try to open it. If not, the only way is to restore from mnemonic phrase (you did wrote it down, didn't you?) or restore from backup, which also may be present there.

**Comment by scissors14** [comment]
The app itself won't open, it just says initializing RPCnode, has some sort of windows vista loading circle around cursor then crashes.

**Comment by aivve** [comment]
Try to delete blockchain and wallet files in C:\Users\%USERNAME%\AppData\Roaming\karbowanec\ and start over.

**Comment by scissors14** [comment]
thanks, that fixed it for me.
