### ISSUE TITLE
Update the link in the "About" section of this repo

### ISSUE THREAD

**Issue by putsan** [seredat/karbowanecwallet#64]
Please replace the old link (http://karbowanec.com) with the new one - https://karbo.org
![image](https://user-images.githubusercontent.com/11944886/162626584-6047b591-62ae-4b1c-8a4a-c4cc50425193.png)

**Comment by aivve** [comment]
Ty, will do but this requires to also update translations, perhaps need to rework this window entirely. For now there's a redirect from http://karbowanec.com/ to https://karbo.org/

**Comment by putsan** [comment]
@aivve okay, now redirect works great, but the first time, when I've visited redirect isn't worked
